.\" 
.\" Copyright (c) 2006, Stefan Walter
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without 
.\" modification, are permitted provided that the following conditions 
.\" are met:
.\" 
.\"     * Redistributions of source code must retain the above 
.\"       copyright notice, this list of conditions and the 
.\"       following disclaimer.
.\"     * Redistributions in binary form must reproduce the 
.\"       above copyright notice, this list of conditions and 
.\"       the following disclaimer in the documentation and/or 
.\"       other materials provided with the distribution.
.\"     * The names of contributors to this software may not be 
.\"       used to endorse or promote products derived from this 
.\"       software without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
.\" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS 
.\" OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED 
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF 
.\" THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH 
.\" DAMAGE.
.\" 
.\"
.\" CONTRIBUTORS
.\"  Stef Walter <stef@memberwebs.com>
.\"
.Dd August, 2006
.Dt rrdbot-create 8
.Os rrdbot 
.Sh NAME
.Nm rddbot-create
.Nd create the RRD files for 
.Xr rrdbotd 8
to write values to.
.Sh SYNOPSIS
.Nm
.Op Fl nv
.Op Fl c Ar confdir
.Op Fl w Ar workdir
.Nm 
.Fl V
.Sh DESCRIPTION
.Xr rrdbotd 8
is an SNMP polling daemon. It writes out the polled values to an 
.Xr rrdtool 1 
database. The 
.Nm
tool can create those RRD files for you. 
.Pp
.Nm 
uses configuration files, one per RRD, to determine where and how to do its 
work. Details of these files and which settings to put in them are found in the 
.Xr rrdbot.conf 5
manual under the CREATE SECTION heading.
.Pp
By default th RRD files are created in the default work directory (see the FILE 
LOCATIONS section below). Files that already exist are not overwritten or 
modified in any way.
.Pp
You can use the 
.Fl n
option to see the 
.Xr rrdtool 1
commands that would be executed. This is useful if you want to customize the 
commands before running them. 
.Sh OPTIONS
The options are as follows. 
.Bl -tag -width Fl
.It Fl c Ar confdir
The directory in which configuration files are stored. See below for info
on the various file locations.
.It Fl n 
Rather than create the files, print the 
.Xr rrdtool 1
commands that would be used to create the files.
.It Fl v
Print verbose messages.
.It Fl V
Prints the version of
.Nm
and the locations of the configuration files, RRD files etc.
.It Fl w Ar workdir
The default directory where to look for RRD files. See below for info on 
the various file locations.
.El
.Sh FILE LOCATIONS
To determine the default location for the configuration files and RRD files 
run this command:
.Bd -literal -offset indent
# rrdbotd -V 
.Ed
.Pp
The configuration files for SNMP pollers are laid out in a directory tree, 
with one file per RRD. Subdirectories can be used to organize the 
configuration files. The contents of the configuration files are described 
in 
.Xr rrdbot.conf 5 .
.Pp
By default the RRD files mirror the directory structure and names of the 
configuration files, with an 
.Pa .rrd
extension appended to the filename.
.Pp
For example if your configuration files are in a structure like the following:
.Bd -literal -offset indent
/usr/local/etc/rrdbot/
  gateways/
    gateway-load.conf
    gateway-traffic.conf
  temperature/
    inside-temperature.conf
    outside-temperature.conf
  machine-load.conf  
.Ed
.Pp
Then the default RRD files would be in a similar directory structure:
.Bd -literal -offset indent
/var/db/rrdbot/
  gateways/
    gateway-load.conf.rrd
    gateway-traffic.conf.rrd
  temperature/
    inside-temperature.conf.rrd
    outside-temperature.conf.rrd
  machine-load.conf.rrd
.Ed
.Pp
The default location for an RRD file can be overridden by using the 
.Ar rrd
option in the configuration file.
.Sh SEE ALSO
.Xr rrdbotd 8 ,
.Xr rrdbot.conf 5 ,
.Xr rrdbot-get 1 ,
.Xr rrdtool 1
.Sh AUTHOR
.An Stef Walter Aq stef@memberwebs.com
